# Generated by Django 3.2.7 on 2022-08-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Registration',
        ),
    ]
